# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Repository in ArgoCD apps are hosted.
repository:

  # -- URL for repository
  url: ""

  # -- Path in repository
  path: ""

  # -- Target branch in repository.
  branch: "main"

# Target cluster where app will be deployed
destination:

  # -- URL for cluster
  url: ""
