{{- $cluster_name := .Values.cluster.name | required ".Values.cluster.name is required." -}}
{{- $cluster_role_arn := .Values.cluster.role_arn | required ".Values.cluster.role_arn is required." -}}
{{- $cluster_ca_data := .Values.cluster.ca_data | required ".Values.cluster.ca_data is required." -}}
{{- $cluster_arn := .Values.cluster.arn | required ".Values.cluster.arn is required." -}}
{{- $cluster_endpoint := .Values.cluster.endpoint | required ".Values.cluster.endpoint is required." -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: cluster
  name: {{ $cluster_name }}
  namespace: argocd
type: Opaque
stringData:
  config: |
    {
      "awsAuthConfig": {
        "clusterName": "{{ $cluster_name }}",
        "roleARN": "{{ $cluster_role_arn }}"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": "{{ $cluster_ca_data }}"
      }
    }
  name: {{ $cluster_arn }}
  server: {{ $cluster_endpoint }}
